import { test, expect } from "@playwright/test";
test("plumber vertical slice, empty state, persistence, repeat playback, and mobile layout", async ({ page, request }) => {
  await page.goto("/");
  await expect(page.getByRole("region", { name: "Demo data source" })).toContainText("Sample activity");
  await expect(page.getByRole("region", { name: "Demo data source" })).toContainText("These events were not received from Ring");
  await expect(page.getByRole("region", { name: "Demo data source" })).toContainText("Local demo answers");
  await expect(page.getByRole("heading", { name: "Home, in the know." })).toBeVisible();
  await page.getByRole("button", { name: "Did the plumber come?", exact: true }).click();
  await expect(page.getByText("I don't have a matching expectation", { exact: false })).toBeVisible();
  await page.getByRole("button", { name: "Tell Around", exact: true }).last().click();
  const dialog = page.getByRole("dialog");
  await dialog.getByRole("textbox").fill("The plumber is coming today between 10 and 1.");
  await dialog.getByRole("button", { name: "Save expectation" }).click();
  await expect(dialog.getByText("Expectation saved")).toBeVisible();
  await dialog.getByRole("button", { name: "Back to my home" }).click();
  await page.getByRole("button", { name: "Play sample visit" }).click();
  await expect(page.getByRole("heading", { name: "Probable visit", exact: true })).toHaveCount(1);
  await expect(page.getByText("Likely matches your plumber visit")).toBeVisible();
  await page.getByRole("button", { name: "Did the plumber come?", exact: true }).click();
  await expect(page.locator(".answer-card")).toContainText("10:41 AM");
  await expect(page.locator(".answer-card")).toContainText("11:27 AM");
  await expect(page.locator(".answer-card")).toContainText("can't confirm who visited");
  await page.screenshot({ path: "test-results/around-desktop.png", fullPage: true });
  await page.getByRole("button", { name: "Anything I should know?", exact: true }).click();
  await expect(page.locator(".answer-card")).toContainText("1 probable visit");
  await page.reload();
  await expect(page.getByText("Likely matches your plumber visit")).toBeVisible();
  await page.getByRole("button", { name: "Play sample visit" }).click();
  await expect(page.getByText("Already up to date.", { exact: false })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Probable visit", exact: true })).toHaveCount(1);
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole("heading", { name: "Home, in the know." })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: "test-results/around-mobile.png", fullPage: true });
  const forbidden = await request.post("/api/ring/sync", { headers: { Origin: "https://unrelated.invalid" }, data: {} });
  expect(forbidden.status()).toBe(403);
  const webhook = await request.post("/api/ring/webhook", { data: {} });
  expect(webhook.status()).toBe(409);
});
